DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS score;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  isadmin INTEGER NOT NULL

);

CREATE TABLE score (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  maxcombo INTEGER NOT NULL,
  score INTEGER NOT NULL,
  shareable TEXT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES user (id)
);

CREATE TABLE puzzle (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  puzzle TEXT NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);